site_name: Ping Identity DevOps Helm Charts
repo_name: pingidentity/helm-charts
repo_url: https://github.com/pingidentity/helm-charts
site_url: https://helm.pingidentity.com/
copyright: © Copyright 2020 Ping Identity
extra_css:
  - mkdocs/overrides/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/mkdocs/overrides
  favicon: images/favicon.png

  features:
    - navigation.tabs
    - instant

  palette:
    # scheme: preference
    primary: indigo
    accent: blue

edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

nav:
  - Welcome:
      - Installation: "index.md"
      - Getting Started: "getting-started.md"
      - Release Notes: "release-notes.md"
  - Value Configs:
      - Introduction: "config/index.md"
      - global: "config/global.md"
      - Container: "config/container.md"
      - External Image: "config/external-image.md"
      - Image: "config/image.md"
      - Ingress: "config/ingress.md"
      - License: "config/license.md"
      - Probes: "config/probes.md"
      - PrivateCerts: "config/private-cert.md"
      - Service: "config/service.md"
      - Vault: "config/vault.md"
      - VolumeMounts: "config/volume-mounts.md"
      - Workload: "config/workload.md"
  - Examples:
      - Introduction: "examples/index.md"
